AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Project:
    Type: String
  VPC:
    Type: String
  Cidr:
    Type: String

Resources:
  Subnet: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: ap-northeast-1a
      CidrBlock: !Sub '${Cidr}/24' 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${Project}-subnet-1a"
        - Key: Project
          Value: !Ref Project
