AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Project:
    Type: String
  Cidr:
    Type: String

Resources:
  VPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Sub '${Cidr}/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags: 
        - Key: Name
          Value: !Sub "${Project}-vpc"
        - Key: Project
          Value: !Ref Project

  Subnets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'nest/subnet.yml'
      Parameters:
        Project: !Ref Project
        VPC: !Ref VPC
        Cidr: !Ref Cidr
    DependsOn: VPC

